# Generated by Django 4.2.14 on 2024-09-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JumpSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('available_slots', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experienced.plane')),
                ('users', models.ManyToManyField(blank=True, related_name='jump_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JumpBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('jump_type', models.CharField(choices=[('TRACKING', 'Tracking Jump'), ('SOLO', 'Solo Jump'), ('AFF', 'Accelerated Freefall (AFF)'), ('WINGSUIT', 'Wingsuit Jump')], default='SOLO', max_length=20)),
                ('plane_departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experienced.jumpslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
