# Generated by Django 4.2.14 on 2024-08-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experienced', '0002_alter_jumpslot_jump_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumpbooking',
            old_name='jump_slot',
            new_name='plane_departure',
        ),
    ]
