# Generated by Django 4.2.14 on 2024-08-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experienced', '0003_rename_jump_slot_jumpbooking_plane_departure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumpslot',
            old_name='jump_date',
            new_name='departure',
        ),
    ]
