# Generated by Django 4.2.14 on 2024-08-20 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experienced', '0004_rename_jump_date_jumpslot_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpslot',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='jumpslot',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='jump_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
