# Generated by Django 4.2.14 on 2024-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experienced', '0005_jumpslot_slug_jumpslot_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpbooking',
            name='jump_type',
            field=models.CharField(choices=[('TRACKING', 'Tracking Jump'), ('SOLO', 'Solo Jump'), ('AFF', 'Accelerated Freefall (AFF)'), ('WINGSUIT', 'Wingsuit Jump')], default='SOLO', max_length=20),
        ),
    ]
