# Generated by Django 4.2.14 on 2024-09-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TandemDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_tandems', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='TandemTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('max_tandems', models.PositiveIntegerField(default=6)),
                ('booked_tandems', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='tandems.tandemday')),
            ],
            options={
                'unique_together': {('day', 'time')},
            },
        ),
    ]
